from __future__ import annotations

import argparse
from pathlib import Path

from mini_pgolf.checkpoint import load_checkpoint
from mini_pgolf.generate import generate_bytes
from mini_pgolf.tokenizer import ByteTokenizer
from mini_pgolf.utils import pick_device


def allowed_ids_from_text(path: str | None) -> set[int] | None:
    if path is None:
        return None
    file_path = Path(path)
    if not file_path.exists():
        return None
    return set(ByteTokenizer().encode(file_path.read_text(encoding="utf-8")))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", default="outputs/mps_baseline/checkpoint.pt")
    parser.add_argument("--device", default="auto")
    parser.add_argument("--max-new-bytes", type=int, default=120)
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top-k", type=int, default=40)
    parser.add_argument("--prompt", default=None)
    parser.add_argument(
        "--chat-template",
        action="store_true",
        help="Wrap prompts as 'User: ...\\nAssistant:' for dialogue-trained checkpoints",
    )
    parser.add_argument(
        "--stop-at-user",
        action="store_true",
        help="Trim output before the next '\\nUser:' marker",
    )
    parser.add_argument(
        "--allowed-text",
        default="data/tiny.txt",
        help="Constrain generated bytes to bytes observed in this text file; use none to disable",
    )
    args = parser.parse_args()
    device = pick_device(args.device)
    model = load_checkpoint(args.checkpoint, device)
    allowed_text = None if args.allowed_text == "none" else args.allowed_text
    allowed_token_ids = allowed_ids_from_text(allowed_text)
    if args.prompt is not None:
        prompt = f"User: {args.prompt}\nAssistant:" if args.chat_template else args.prompt
        text = generate_bytes(
            model,
            prompt,
            args.max_new_bytes,
            args.temperature,
            args.top_k,
            device,
            allowed_token_ids,
        )
        if args.stop_at_user:
            text = text.split("\nUser:", maxsplit=1)[0]
        print(text)
        return
    print(f"Loaded {args.checkpoint} on {device}. Press Ctrl-D to exit.")
    while True:
        try:
            prompt = input("you> ")
        except EOFError:
            print()
            break
        rendered_prompt = f"User: {prompt}\nAssistant:" if args.chat_template else prompt
        text = generate_bytes(
            model,
            rendered_prompt,
            args.max_new_bytes,
            args.temperature,
            args.top_k,
            device,
            allowed_token_ids,
        )
        if args.stop_at_user:
            text = text.split("\nUser:", maxsplit=1)[0]
        if args.chat_template and text.startswith(rendered_prompt):
            text = text[len(rendered_prompt) :].lstrip()
        print("model> " + text)


if __name__ == "__main__":
    main()
